import jsPDF from "jspdf";

import { round, type AnalysisData, type GpaResult, type Scenario } from "./gpa";

/* ------------------------------------------------------------------ */
/* Layout constants — A4 portrait, points                              */
/* ------------------------------------------------------------------ */
const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;

const NAVY: [number, number, number] = [23, 37, 74];
const NAVY_SOFT: [number, number, number] = [238, 241, 248];
const RED: [number, number, number] = [166, 25, 46];
const INK: [number, number, number] = [28, 32, 42];
const MUTED: [number, number, number] = [110, 118, 134];
const LINE: [number, number, number] = [214, 219, 229];
const ZEBRA: [number, number, number] = [248, 249, 252];

const FOOTER_TOP = PAGE_H - 62;

interface Ctx {
  doc: jsPDF;
  y: number;
  page: number;
}

function setFill(doc: jsPDF, c: [number, number, number]) {
  doc.setFillColor(c[0], c[1], c[2]);
}
function setText(doc: jsPDF, c: [number, number, number]) {
  doc.setTextColor(c[0], c[1], c[2]);
}
function setStroke(doc: jsPDF, c: [number, number, number]) {
  doc.setDrawColor(c[0], c[1], c[2]);
}

function drawPageHeader(ctx: Ctx, courseName: string) {
  const { doc } = ctx;
  if (ctx.page === 1) return;
  setText(doc, MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("UCP AI GPA Analyzer — Academic Result Report", MARGIN, 34);
  doc.text(courseName, PAGE_W - MARGIN, 34, { align: "right" });
  setStroke(doc, LINE);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, 42, PAGE_W - MARGIN, 42);
}

function drawPageFooter(ctx: Ctx) {
  const { doc } = ctx;
  setStroke(doc, LINE);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, FOOTER_TOP, PAGE_W - MARGIN, FOOTER_TOP);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setText(doc, MUTED);
  doc.text("Designed & Developed by Aqib Ahmed  ·  aqibah50@gmail.com", MARGIN, FOOTER_TOP + 14);
  doc.text(
    "Disclaimer: This report is generated by an independent academic utility for UCP students.",
    MARGIN,
    FOOTER_TOP + 25,
  );
  doc.text(`Page ${ctx.page}`, PAGE_W - MARGIN, FOOTER_TOP + 14, { align: "right" });
}

function newPage(ctx: Ctx, courseName: string) {
  drawPageFooter(ctx);
  ctx.doc.addPage();
  ctx.page += 1;
  drawPageHeader(ctx, courseName);
  ctx.y = 66;
}

function ensure(ctx: Ctx, needed: number, courseName: string) {
  if (ctx.y + needed > FOOTER_TOP - 12) newPage(ctx, courseName);
}

function sectionTitle(ctx: Ctx, title: string, courseName: string) {
  ensure(ctx, 40, courseName);
  const { doc } = ctx;
  setFill(doc, RED);
  doc.rect(MARGIN, ctx.y - 8, 3, 13, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setText(doc, NAVY);
  doc.text(title.toUpperCase(), MARGIN + 10, ctx.y + 2);
  ctx.y += 10;
  setStroke(doc, LINE);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, ctx.y, PAGE_W - MARGIN, ctx.y);
  ctx.y += 16;
}

/** Two-column definition grid inside a bordered card. */
function infoCard(ctx: Ctx, rows: [string, string][], courseName: string) {
  const cols = 2;
  const lines = Math.ceil(rows.length / cols);
  const rowH = 24;
  const cardH = lines * rowH + 16;
  ensure(ctx, cardH + 10, courseName);
  const { doc } = ctx;
  setStroke(doc, LINE);
  setFill(doc, [255, 255, 255]);
  doc.setLineWidth(0.7);
  doc.roundedRect(MARGIN, ctx.y, CONTENT_W, cardH, 4, 4, "FD");

  const colW = CONTENT_W / cols;
  rows.forEach((r, i) => {
    const col = i % cols;
    const line = Math.floor(i / cols);
    const x = MARGIN + col * colW + 14;
    const y = ctx.y + 20 + line * rowH;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    setText(doc, MUTED);
    doc.text(r[0].toUpperCase(), x, y);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    setText(doc, INK);
    doc.text(doc.splitTextToSize(r[1] || "—", colW - 28)[0], x, y + 12);
  });
  ctx.y += cardH + 20;
}

interface Col {
  header: string;
  width: number;
  align?: "left" | "right";
}

function table(ctx: Ctx, cols: Col[], rows: string[][], courseName: string, muteRow?: (i: number) => boolean) {
  const { doc } = ctx;
  const headerH = 22;

  const drawHead = () => {
    ensure(ctx, headerH + 24, courseName);
    setFill(doc, NAVY);
    doc.rect(MARGIN, ctx.y, CONTENT_W, headerH, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setText(doc, [255, 255, 255]);
    let x = MARGIN;
    cols.forEach((c) => {
      const tx = c.align === "right" ? x + c.width - 8 : x + 8;
      doc.text(c.header.toUpperCase(), tx, ctx.y + 14, { align: c.align === "right" ? "right" : "left" });
      x += c.width;
    });
    ctx.y += headerH;
  };

  drawHead();

  rows.forEach((row, ri) => {
    const cells = row.map((cell, ci) => doc.splitTextToSize(cell, (cols[ci]?.width ?? 100) - 16) as string[]);
    const lineCount = Math.max(...cells.map((c) => c.length));
    const rowH = Math.max(20, lineCount * 11 + 9);

    if (ctx.y + rowH > FOOTER_TOP - 12) {
      newPage(ctx, courseName);
      drawHead();
    }

    if (ri % 2 === 1) {
      setFill(doc, ZEBRA);
      doc.rect(MARGIN, ctx.y, CONTENT_W, rowH, "F");
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    setText(doc, muteRow?.(ri) ? MUTED : INK);

    let x = MARGIN;
    cells.forEach((lines, ci) => {
      const c = cols[ci]!;
      const tx = c.align === "right" ? x + c.width - 8 : x + 8;
      lines.forEach((ln, li) => {
        doc.text(ln, tx, ctx.y + 14 + li * 11, { align: c.align === "right" ? "right" : "left" });
      });
      x += c.width;
    });

    setStroke(doc, LINE);
    doc.setLineWidth(0.4);
    doc.line(MARGIN, ctx.y + rowH, PAGE_W - MARGIN, ctx.y + rowH);
    ctx.y += rowH;
  });

  ctx.y += 22;
}

function resultBanner(ctx: Ctx, result: GpaResult, courseName: string) {
  const { doc } = ctx;
  const h = 78;
  ensure(ctx, h + 10, courseName);
  setFill(doc, NAVY);
  doc.roundedRect(MARGIN, ctx.y, CONTENT_W, h, 5, 5, "F");
  setFill(doc, RED);
  doc.rect(MARGIN, ctx.y + h - 4, CONTENT_W, 4, "F");

  const cells: [string, string][] = [
    ["Percentage", `${round(result.percentage)}%`],
    ["Grade", result.grade],
    ["Grade Point", result.gradePoint.toFixed(2)],
    ["GPA (Course)", result.gradePoint.toFixed(2)],
  ];
  const cw = CONTENT_W / cells.length;
  cells.forEach((c, i) => {
    const cx = MARGIN + i * cw + cw / 2;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    setText(doc, [190, 199, 218]);
    doc.text(c[0].toUpperCase(), cx, ctx.y + 26, { align: "center" });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    setText(doc, [255, 255, 255]);
    doc.text(c[1], cx, ctx.y + 52, { align: "center" });
    if (i > 0) {
      setStroke(doc, [60, 76, 116]);
      doc.setLineWidth(0.6);
      doc.line(MARGIN + i * cw, ctx.y + 16, MARGIN + i * cw, ctx.y + h - 16);
    }
  });
  ctx.y += h + 22;
}

function coverHeader(ctx: Ctx, data: AnalysisData) {
  const { doc } = ctx;
  const h = 96;
  setFill(doc, NAVY);
  doc.rect(0, 0, PAGE_W, h, "F");
  setFill(doc, RED);
  doc.rect(0, h, PAGE_W, 4, "F");

  setFill(doc, [255, 255, 255]);
  doc.roundedRect(MARGIN, 28, 44, 44, 5, 5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  setText(doc, NAVY);
  doc.text("UCP", MARGIN + 22, 56, { align: "center" });

  doc.setFontSize(17);
  setText(doc, [255, 255, 255]);
  doc.text("UCP AI GPA Analyzer", MARGIN + 60, 48);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  setText(doc, [190, 199, 218]);
  doc.text("Official-format Academic Result Report", MARGIN + 60, 64);
  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleString()}`, PAGE_W - MARGIN, 48, { align: "right" });
  doc.text(data.courseType === "Lab" ? "Lab Course" : "Theory Course", PAGE_W - MARGIN, 64, { align: "right" });

  ctx.y = h + 40;
}

export function downloadResultPdf(data: AnalysisData, result: GpaResult, scenarios: Scenario[]) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const ctx: Ctx = { doc, y: 0, page: 1 };
  const courseName = data.courseName || "Course";
  const extra = data as AnalysisData & {
    studentId?: string;
    courseCode?: string;
    semester?: string;
  };

  coverHeader(ctx, data);

  sectionTitle(ctx, "Student Information", courseName);
  infoCard(
    ctx,
    [
      ["Student Name", data.studentName || "—"],
      ["Student ID", extra.studentId || "—"],
    ],
    courseName,
  );

  sectionTitle(ctx, "Course Information", courseName);
  infoCard(
    ctx,
    [
      ["Course Name", courseName],
      ["Course Code", extra.courseCode || "—"],
      ["Course Type", data.courseType],
      ["Semester", extra.semester || "—"],
      ["Evaluation Weight Covered", `${round(result.totalWeight)}%`],
      ["Categories Evaluated", String(result.categories.length)],
    ],
    courseName,
  );

  sectionTitle(ctx, "Result Summary", courseName);
  resultBanner(ctx, result, courseName);

  sectionTitle(ctx, "Evaluation Policy Used", courseName);
  table(
    ctx,
    [
      { header: "Category", width: CONTENT_W * 0.4 },
      { header: "Selection Rule", width: CONTENT_W * 0.35 },
      { header: "Weight", width: CONTENT_W * 0.25, align: "right" },
    ],
    result.categories.map((c) => [c.name, ruleLabel(c.rule), `${round(c.weightPercent)}%`]),
    courseName,
  );

  sectionTitle(ctx, "Marks Breakdown", courseName);
  const breakdownRows: string[][] = [];
  const mutedRows = new Set<number>();
  for (const c of result.categories) {
    const assessments = [
      ...c.usedItems.map((i) => `${i.label}: ${i.obtained}/${i.total}`),
      ...c.droppedItems.map((i) => `${i.label}: ${i.obtained}/${i.total} (dropped)`),
    ].join("\n");
    breakdownRows.push([
      c.name,
      assessments || "—",
      `${round(c.weightPercent)}%`,
      `${round(c.scorePercent)}%`,
      `${round(c.weightedScore)}`,
    ]);
  }
  table(
    ctx,
    [
      { header: "Category", width: CONTENT_W * 0.22 },
      { header: "Assessments", width: CONTENT_W * 0.38 },
      { header: "Weight", width: CONTENT_W * 0.13, align: "right" },
      { header: "Score", width: CONTENT_W * 0.13, align: "right" },
      { header: "Weighted", width: CONTENT_W * 0.14, align: "right" },
    ],
    breakdownRows,
    courseName,
    (i) => mutedRows.has(i),
  );

  sectionTitle(ctx, "Scenario Analysis", courseName);
  table(
    ctx,
    [
      { header: "Scenario", width: CONTENT_W * 0.46 },
      { header: "Percentage", width: CONTENT_W * 0.18, align: "right" },
      { header: "Grade", width: CONTENT_W * 0.18, align: "right" },
      { header: "Grade Point", width: CONTENT_W * 0.18, align: "right" },
    ],
    scenarios.map((s) => [s.label, `${round(s.percentage)}%`, s.grade, s.gradePoint.toFixed(2)]),
    courseName,
  );

  if (data.notes) {
    sectionTitle(ctx, "Notes", courseName);
    const lines = doc.splitTextToSize(data.notes, CONTENT_W - 24) as string[];
    ensure(ctx, lines.length * 11 + 24, courseName);
    setFill(doc, NAVY_SOFT);
    doc.roundedRect(MARGIN, ctx.y, CONTENT_W, lines.length * 11 + 20, 4, 4, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    setText(doc, INK);
    lines.forEach((ln, i) => doc.text(ln, MARGIN + 12, ctx.y + 16 + i * 11));
    ctx.y += lines.length * 11 + 30;
  }

  drawPageFooter(ctx);

  doc.save(`ucp-gpa-report-${courseName.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "result"}.pdf`);
}

function ruleLabel(rule: string) {
  if (rule === "all") return "All assessments (aggregate)";
  if (rule === "average") return "Average of all assessments";
  if (rule.startsWith("top")) return `Best ${rule.replace("top", "")} counted`;
  return rule;
}
