/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as CgpaCalculatorRouteImport } from './routes/cgpa-calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GpaCalculatorRouteImport } from './routes/gpa-calculator'
import { Route as GradeScaleRouteImport } from './routes/grade-scale'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const CgpaCalculatorRoute = CgpaCalculatorRouteImport.update({
  id: '/cgpa-calculator',
  path: '/cgpa-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GpaCalculatorRoute = GpaCalculatorRouteImport.update({
  id: '/gpa-calculator',
  path: '/gpa-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeScaleRoute = GradeScaleRouteImport.update({
  id: '/grade-scale',
  path: '/grade-scale',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/cgpa-calculator': typeof CgpaCalculatorRoute
  '/contact': typeof ContactRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/grade-scale': typeof GradeScaleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/cgpa-calculator': typeof CgpaCalculatorRoute
  '/contact': typeof ContactRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/grade-scale': typeof GradeScaleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/cgpa-calculator': typeof CgpaCalculatorRoute
  '/contact': typeof ContactRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/grade-scale': typeof GradeScaleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyze'
    | '/cgpa-calculator'
    | '/contact'
    | '/gpa-calculator'
    | '/grade-scale'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyze'
    | '/cgpa-calculator'
    | '/contact'
    | '/gpa-calculator'
    | '/grade-scale'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyze'
    | '/cgpa-calculator'
    | '/contact'
    | '/gpa-calculator'
    | '/grade-scale'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CgpaCalculatorRoute: typeof CgpaCalculatorRoute
  ContactRoute: typeof ContactRoute
  GpaCalculatorRoute: typeof GpaCalculatorRoute
  GradeScaleRoute: typeof GradeScaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgpa-calculator': {
      id: '/cgpa-calculator'
      path: '/cgpa-calculator'
      fullPath: '/cgpa-calculator'
      preLoaderRoute: typeof CgpaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpa-calculator': {
      id: '/gpa-calculator'
      path: '/gpa-calculator'
      fullPath: '/gpa-calculator'
      preLoaderRoute: typeof GpaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-scale': {
      id: '/grade-scale'
      path: '/grade-scale'
      fullPath: '/grade-scale'
      preLoaderRoute: typeof GradeScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyzeRoute: AnalyzeRoute,
  CgpaCalculatorRoute: CgpaCalculatorRoute,
  ContactRoute: ContactRoute,
  GpaCalculatorRoute: GpaCalculatorRoute,
  GradeScaleRoute: GradeScaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
